apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: issuer
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: "raihanboss2005@gmail.com"
    privateKeySecretRef:
      name: issuer
    solvers:
    - dns01:
        route53:
          hostedZoneID: Z06556183IVGA9H4A78BW
          region: eu-west-2
    - http01:
        ingress:
          class: nginx
