apiVersion: argopro.io/v1aplha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/Raihan-chowdhury7/EKS_Practice.git'
    targetRevision: HEAD
    path: apps

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apps

  syncPolicy:
    automated:
    prune: true
    selfHeal: true
  syncOptions:
  - CreateNamespace=true